language: node_js
node_js:
  - "6"
sudo: required
services:
  - mongodb
  - docker
cache:
  directories:
    - node_modules
before_install:
  - npm i mongodb-download@2.2.3
script:
  - npm install
  - npm run lint
  - npm run build
  - npm test
  - sh ./buildDockerImage.sh


